### ISSUE TITLE
Adding Cloud Logging Service instance creation and binding to service as part of mta using cds add mta

### ISSUE THREAD

**Issue by gopalanand333** [cap-js/telemetry#146]
Hi,
Currently if we want to deploy application to the cloud foundry runtime + cloud logging service, we need to manually add the service instance configuration and binding to srv. This does leads to error if someone miss configures the ingest configuration.

```
     - name: incidents-cloud-logging  
       type: org.cloudfoundry.managed-service  
       parameters: 
         service: cloud-logging  
         service-plan: standard  
         config:
          ingest_otlp: 
            enabled: true 
```
steps defined here: https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/observability/4-deploy-to-cf.md#set-up-the-sap-cloud-logging-service. 
If cds add mta or adding the telemetry plugin can add the configuration to mta automatically, 
It will improve user experience and avoid any chances of error due to miss configured mta.
