### ISSUE TITLE
Kind telemetry-to-otlp requires additional settings when used with GRPC

### ISSUE THREAD

**Issue by a-thaler** [cap-js/telemetry#325]
**Description**

Documentation says:
```md
Use via cds.requires.telemetry.kind = 'to-otlp'.

Required additional dependencies (* = grpc|proto|http):

@grpc/grpc-js (in case of OTLP/gRPC)
@opentelemetry/exporter-trace-otlp-*
@opentelemetry/exporter-metrics-otlp-*
```

In my project I used these dependencies:
```yaml
  "dependencies": {
    "@sap/cds": "^8",
    "express": "^4",
    "@cap-js/hana": "^1",
    "@cap-js/telemetry": "^1.2.3",
    "@grpc/grpc-js": "^1.9.14",
    "@opentelemetry/exporter-metrics-otlp-grpc": "^0.57.0",
    "@opentelemetry/exporter-trace-otlp-grpc": "^0.57.0"
  },
  "cds": {
    "requires": {
      "telemetry": {
        "kind": "to-otlp"
      }
}
````

This setup fails at startup with:
```sh
Error: Cannot find module '@opentelemetry/exporter-trace-otlp-proto'. Make sure to install it with 'npm i @opentelemetry/exporter-trace-otlp-proto'
Cannot find module '@opentelemetry/exporter-trace-otlp-proto'
Require stack:
- /app/node_modules/@cap-js/telemetry/lib/utils.js
- /app/node_modules/@cap-js/telemetry/lib/tracing/index.js
- /app/node_modules/@cap-js/telemetry/lib/index.js
- /app/node_modules/@cap-js/telemetry/cds-plugin.js
- /app/node_modules/@sap/cds/lib/utils/cds-utils.js
- /app/node_modules/@sap/cds/lib/index.js
- /app/node_modules/@sap/cds/bin/serve.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.<anonymous> (node:internal/modules/cjs/loader:1055:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Module.require (node:internal/modules/cjs/loader:1311:12)
    at require (node:internal/modules/helpers:136:16)
    at _require (/app/node_modules/@cap-js/telemetry/lib/utils.js:173:12)
    at _getExporter (/app/node_modules/@cap-js/telemetry/lib/tracing/index.js:100:79)
```

Adding additional config fixes the problem
```yaml
  "requires": {
        "telemetry": {
          "kind": "to-otlp",
          "tracing": {
            "exporter": {
              "module": "@opentelemetry/exporter-trace-otlp-grpc",
              "class": "OTLPTraceExporter"
            }
          },
          "metrics": {
            "exporter": {
              "module": "@opentelemetry/exporter-metrics-otlp-grpc",
              "class": "OTLPMetricExporter"
            }
          }
   }
```

However, that defeats the purpose of the kind. I would expect that the setup will work without additional configuration according to the documentation.
