### ISSUE TITLE
cds add dynatrace generates invalid environment_name configuration in mta.yaml

### ISSUE THREAD

**Issue by gopalanand333** [cap-js/telemetry#326]
When Running the command `cds add dynatrace` in mta the following configuration gets added:
```
  - name: incidents-dynatrace
    type: org.cloudfoundry.managed-service
    parameters:
      service: dynatrace
      service-plan: environment
      config:
        environment_name: incidents
```

Here **environment_name** is in lowercase matching the project name specified in package.json.
The dynatrace instance creation requires environment_name in the following format: **Name for the environment, maximum 16 uppercase letters and numbers.**

![Image](https://github.com/user-attachments/assets/4bfaed38-92b4-4e44-9dc6-403042416083)
